
```{r prep,include=F}
library(tidyverse)
library(officer)
library(flextable)
library(htmlwidgets)

stock_summary_df <- tibble("Convention General Principles"=c("Restore or maintain at Bmsy","Eliminate overfishing","Apply Percautionary Approach","Minimise harmful impacts on living marine resources and ecosystems","Preserve marine biodiversity"), 
                           "Status"=c("Unknown","OK","Not accomplished","Intermediate","Unknown"),
                           "Comment/consideration"=c("Bmsy unknown","Fishing mortality low","Reference points not defined","VME closures in effect, low bycatch reported","Cannot be evaluated"))
                           
                           
green_light <- file.path("green-light.jpg")                           
yellow_light <- file.path("yellow-light.jpg")                           
red_light <- file.path("red-light.jpg")                           
white_light <- file.path("white-light.jpg")                           


                           
summary_table <- flextable(stock_summary_df) %>% 
    align(align="left",part="all") %>% 
    autofit() %>% 
    compose(j=1,i=1,part="body",
                value= as_paragraph("Restore or maintain at ",as_i("B"),as_i(as_sub("MSY")))) %>% 
    compose(j=3,i=1,part="body",
            value= as_paragraph(as_i("B"),as_i(as_sub("MSY")))) %>% 
    compose(j=2,i=which(stock_summary_df$Status=="OK"),part="body",
            value= as_paragraph(as_image(src = green_light, width = .20, height = .20))) %>% 
    compose(j=2,i=which(stock_summary_df$Status=="Intermediate"),part="body",
            value= as_paragraph(as_image(src = yellow_light, width = .20, height = .20))) %>% 
    compose(j=2,i=which(stock_summary_df$Status=="Not accomplished"),part="body",
            value= as_paragraph(as_image(src = red_light, width = .20, height = .20))) %>% 
    compose(j=2,i=which(stock_summary_df$Status=="Unknown"),part="body",
            value= as_paragraph(as_image(src = white_light, width = .20, height = .20))) %>% 
    italic(i=1,part="header") 
```

###Species


> grey box
grey box text here



**Management objectives**
No explicit management plan or management objectives have been defined by Commission. Convention General Principles are applied. Advice is based on survey indices and catch trends in relation to estimates of recruitment.



**Management unit**
The management unit is confined to NAFO Div. 3NO, which is a portion of the stock that is distributed in NAFO Div. 3NO and Subdivision 3Ps.

**Stock status**
The assessment is considered data limited and is associated with a relatively high uncertainty. Biomass of this stock increased in 1999 and 2000, generated by the large recruitment observed in those years. Subsequently, the biomass index decreased and has since remained variable but lower. No large recruitments have been observed since 2000. Fishing mortality is low.

**Effects of the fishery on the ecosystem**
No specific information is available. General impacts of fishing gears on the ecosystem should be considered.

**Sources of Information**
SCR Doc. 19/15,20,22; SCS Doc. 19/09,10,11.
