
# Option 2

```{r}
theme_2 <- function(base_size = 9, base_family = "Cambria"){
    ggthemes::theme_foundation(base_size = base_size, base_family = base_family) %+replace%
        theme(rect = element_rect(color = "black", size = 0.5 / ggplot2::.pt, # 0.5 pt to mm
                                  linetype = "solid", fill = NA),
              line = element_line(colour = "black", size = 0.5 / ggplot2::.pt,
                                  linetype = "solid", lineend = "butt"),
              axis.ticks = element_line(colour = "black"),
              axis.ticks.length = unit(-0.15, "cm"),
              axis.text.x = element_text(margin = unit(c(0.25, 0.1, 0.1, 0.1), "cm")),
              axis.text.y = element_text(margin = unit(c(0.1, 0.25, 0.1, 0.1), "cm"), hjust = 1),
              axis.line = element_line(colour = "black"),
              panel.grid.minor = element_blank(),
              panel.grid.major = element_blank(),
              panel.background = element_rect(colour = "black"),
              plot.background = element_blank(),
              strip.background = element_blank(),
              legend.key = element_blank(),
              legend.background = element_blank(),
              legend.box.background = element_rect(color = "black", size = 0.5 / ggplot2::.pt, # 0.5 pt to mm
                                                   linetype = "solid", fill = NA),
              legend.title = element_text(size = base_size - 2, hjust = 0),
              legend.justification = c(1, 1),
              legend.position = c(0.98, 0.98),
              legend.key.size = unit(1, "line"),
              legend.margin = margin(l = 1, r = 1, b = 0.5, t = 0.5, unit = "mm"),
              legend.box.margin = margin(l = 1, r = 1, b = 0.5, t = 0.5, unit = "mm"))
}
theme_set(theme_2())
```


- Font: Cambria 9pt.
- Plot Border: black 0.5 pt. No borders around entire graph, just plot. Borders around legend (0.5pt) if possible.
- Tick Marks to the inside on x & y axis
- Graph lines: 0.75 pt, black if possible, otherwise grey
- Grid lines: None
- Plot size: Height 6.4 cm, width 11.5 cm.

```{r, fig.height = .nafo_height * 2, fig.width = .nafo_width * 2}
summary_plot
```

```{r, fig.height = .nafo_height, fig.width = .nafo_width}
sel_plot
```

\pagebreak

# Option 2

```{r, fig.height = .nafo_height * 2, fig.width = .nafo_width * 2}
species_plot
```

```{r, fig.height = .nafo_height, fig.width = .nafo_width}
res_plot
```

\pagebreak
